### ISSUE TITLE
Documentation on how holesail works

### ISSUE THREAD

**Issue by gene1wood** [holesail/holesail#18]
I looked but wasn't able to find this, can you either add a link in the [`README.md`](https://github.com/holesail/holesail/blob/main/README.md) or add a section that summarizes how holesail works? Maybe a diagram?

In reading through the docs I'm unclear on what holesail is from a technology standpoint.

**Comment by supersuryaansh** [comment]
@gene1wood To summarise, you can connect to systems over holesail, with no port forwarding, no static IP, no dynamic DNS. With that, there are unlimited possibility with what you can do with holesail.

But yeah, the docs need good work, I will add more to them. In the meantime, you can check our docs here: https://docs.holesail.io

**Comment by gene1wood** [comment]
@supersuryaansh Thanks for the link to the documentation site.

I guess what I'm asking is not what features and capabilities does holesail provide ("you can connect two systems over holesail, with no port forwarding, no static IP, no dynamic DNS."), I'm asking, from a technology perspective, how does holesail work?

For example, holesail differs from hosting a service on a server with a static IP that a user can connect to, but how does holesail achieve this? Is there a overview description of how holesail works? 

As an example, I'm guessing from the name and from the fact that it depends on holepunch.io that it has something to do with punching firewall holes (through reverse connections).

What would be great is some drawing or summary of what's actually going on under the hood that differentiates this from other solutions (like ngrok, tailscale, netbird, CloudFlare Tunnel, etc)

**Comment by supersuryaansh** [comment]
@gene1wood Holesail uses the pear stack (Holepunch.to) to punch holes through the firewall and NAT and create a connection with other peers.

It uses the Kademlia algorithm to work (the same algorithm as Bit-torrent), there is a good video explaining Kademlia here: https://www.youtube.com/watch?v=1QdKhNpsj8M

That being said, here is a tiny summary:
1. Kademlia has nodes. Currently, there are two nodes run by the Holepunch team.
2. A node is not a STUN server; it is just a special peer that we "know" from the beginning and that knows about many other peers.
3. When you connect using holesail, say to a connection string (Key) "X", Holesail will ping the node and ask if it knows about this peer with key X. The Node may or may not know, but it will share information of other peers that it knows about with Holesail.
4. It will then proceed to ask other Peers if they know about the key; if they know, they will tell us about it, and if they don't, then they will tell us about the neighbour nodes and so on, and eventually, we will find the peer with the key.
5. Once found, we establish a connection with the peer and get on with our business.

I have given a very brief overview, so I highly recommend reading about Kademlia and watching the video above to get a full picture.
