### ISSUE TITLE
[Guide/Help] How does one proxy a UDP/TCP Docker port correctly?

### ISSUE THREAD

**Issue by ThaDaVos** [holesail/holesail#28]
I am running a Palworld server using Pelican (Pterodactyl) fork, but I cannot figure out how to setup Holesail (running on the host) to proxy traffic for my friends so I don't have to open ports through port forwarding - second, would be great if you could forward a TCP/UDP at once with one connecting if possible.

Is there any guide/recommendations on how to properly proxy a Docker container from the host?
I am also looking at https://github.com/anaxios/holesail-docker - to see if that's a solution

**Comment by supersuryaansh** [comment]
@ThaDaVos The UDP functionality is limited at the moment due to a bug and will not function until my next push, but to proxy traffic to and from a TCP port, you can check our docs here: https://docs.holesail.io/usage-guide/set-a-port-live

You will need two different connection strings to forward two different ports, though; this will change in the future.

**Comment by ThaDaVos** [comment]
I meant forwarding the same port but on TCP and UDP at once - still need two connections for that? 

Any ETA on the UDP fix?

**Comment by supersuryaansh** [comment]
> I meant forwarding the same port but on TCP and UDP at once - still need two connections for that?
Yes

Any ETA on the UDP fix?
> 2 weeks maximum

**Comment by ThaDaVos** [comment]
Would it be possible to change it so you can do BOTH protocols for the same port? Like port forwarding also does this - I am just asking out of curiosity - if not, then #27 could do it too 

Thanks for the ETA - if you need a tester, I'm willing to help!

**Comment by ThaDaVos** [comment]
@supersuryaansh - I was curious, how is the fix coming along? Need help testing?

**Comment by supersuryaansh** [comment]
@ThaDaVos We are almost there, modules related to Holesail udp support will be updated soon and I will ping you ⛵️😄

**Comment by ThaDaVos** [comment]
Thanks for the update @supersuryaansh !

**Comment by supersuryaansh** [comment]
@ThaDaVos 
https://github.com/holesail/holesail-server/pull/3
https://github.com/holesail/holesail-client/pull/2
https://github.com/holesail/hyper-cmd-lib-net/commit/9fb99b3a5fec1de733c7887be383988af656116b

You can test by using holesail client, and server manually if you want to help testing.

**Comment by ThaDaVos** [comment]
Oh you mean using the NPM modules manually?

**Comment by supersuryaansh** [comment]
@ThaDaVos I have released Holesail version 1.8.3 with UDP patch, it is still a Beta feature and will improve over time.

Make sure you update Holesail through npm or fetch the latest release from Github.

**Comment by ThaDaVos** [comment]
I am currently trying, but the client still says "Holesail TCP Client Started":
![afbeelding](https://github.com/user-attachments/assets/fdf1cb41-e340-4b9a-afab-6676a0f1f9b4)

If I supply `--udp` as argument i get an error:
```
node:events:497
      throw er; // Unhandled 'error' event
      ^

DHTError: HOLEPUNCH_ABORTED: Holepunch aborted
    at holepunch (C:\Users\Dylan\AppData\Roaming\npm\node_modules\holesail\node_modules\hyperdht\lib\connect.js:241:40)
    at async connectAndHolepunch (C:\Users\Dylan\AppData\Roaming\npm\node_modules\holesail\node_modules\hyperdht\lib\connect.js:189:3)
Emitted 'error' event on NoiseSecretStream instance at:
    at ReadableState.afterDestroy (C:\Users\Dylan\AppData\Roaming\npm\node_modules\holesail\node_modules\streamx\index.js:512:19)
    at NoiseSecretStream._destroy (C:\Users\Dylan\AppData\Roaming\npm\node_modules\holesail\node_modules\@hyperswarm\secret-stream\index.js:525:5)
    at ReadableState.updateNonPrimary (C:\Users\Dylan\AppData\Roaming\npm\node_modules\holesail\node_modules\streamx\index.js:399:16)
    at ReadableState.update (C:\Users\Dylan\AppData\Roaming\npm\node_modules\holesail\node_modules\streamx\index.js:380:71)
    at ReadableState.updateReadNT (C:\Users\Dylan\AppData\Roaming\npm\node_modules\holesail\node_modules\streamx\index.js:555:10)
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11) {
  code: 'HOLEPUNCH_ABORTED'
}
```

Command used: 
- Server: `holesail --udp --live 8211 --host {DOCKER_CONTAINER_IP}` - the `{DOCKER_CONTAINER_IP}` I got using `netstat -tlpn | grep 8211`
- Client: `holesail --udp --port 8211 {SECRET}`

In both cases command run as normal user, using version 1.8.4

**Comment by ThaDaVos** [comment]
I just tried on an external linux machine and then the Client command does not error

**Comment by supersuryaansh** [comment]
You need --udp on both client and host side. Also make sure you are on the latest holesail version with UDP support.

The Holepunch aborted error appears when client is behind a VPN, I am aware of this and currently debugging and fix. (UDP is a beta feature)

**Comment by ThaDaVos** [comment]
Just tried with Palworld and it works!
