### ISSUE TITLE
fail to start a connection

### ISSUE THREAD

**Issue by ronnisoderberg** [holesail/holesail#7]
I receive a connection string, but when I try to establish a connection from a client, the server shuts down. I get the same type of shutdown when I switch from server to client and try to connect out from the computer. I ran the debugger and received the error message 
`ECONNRESET as TCP.onStreamRead (node:interval/stream_base_commons:218:20) as TCP.callbackTrampoline (node:interval/async_hooks:130:17).` 

The operating system I am running is Win10 Enterprise version. And using node v20.15.0

**Comment by supersuryaansh** [comment]
The error seems to be related to the "inspect" debugger and not exactly related to holesail. I am not sure what is causing this abrupt shutdown of Holesail, but from your previous description on Discord, it is system-specific.

**Comment by supersuryaansh** [comment]
Can you try running Holesail on a different Windows-enterprise system other than this and see what do you get?

**Comment by supersuryaansh** [comment]
Cleaning up
