### ISSUE TITLE
(Featurerequest) keep holesail running in the background

### ISSUE THREAD

**Issue by Steampowered-hippo** [holesail/holesail#8]
To expose an app on a self hosted server permanently to the clearnet it would be great, to keep holesail running when the terminal closes. Even when the client and/ or the server restarts, they should find each other automatically.

**Comment by supersuryaansh** [comment]
@Steampowered-hippo It is a planned feature and will be implemented soon, in the meanwhile you can use the following methods to run Holesail in background:

1. Screen
2. PM2

**Comment by supersuryaansh** [comment]
@Steampowered-hippo #13 adds this feature. Update to version 1.7.0 and you are all good.

**Comment by Steampowered-hippo** [comment]
😘
